# Generated by Django 3.1.7 on 2021-02-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ['created', 'modified']},
        ),
        migrations.AddField(
            model_name='daily',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
